import type { Client } from "./types";

export const mockClients: Client[] = [
  {
    id: "1",
    name: "María García López",
    email: "maria.garcia@empresa.com.ar",
    phone: "+54 11 4567-8901",
    cuit: "30-71234567-8",
    companyType: "sociedad_anonima",
    companyName: "Tecnologías Avanzadas S.A.",
    submittedAt: "2026-01-24T10:30:00Z",
    status: "pending",
    hasPEP: true,
    pepApprovalStatus: "pending",
    documents: [
      {
        id: "doc1",
        name: "Contrato Social",
        type: "pdf",
        status: "pending",
        required: true,
        url: "/documents/contrato-social.pdf",
        uploadedAt: "2026-01-24T10:30:00Z",
      },
      {
        id: "doc2",
        name: "Acta",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/acta.pdf",
        uploadedAt: "2026-01-24T10:32:00Z",
        reviewedAt: "2026-01-25T09:00:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc3",
        name: "Libro de Socios",
        type: "pdf",
        status: "pending",
        required: true,
        url: "/documents/libro-socios.pdf",
        uploadedAt: "2026-01-24T10:35:00Z",
      },
      {
        id: "doc4",
        name: "Poder",
        type: "pdf",
        status: "rejected",
        required: false,
        url: "/documents/poder.pdf",
        uploadedAt: "2026-01-24T10:40:00Z",
        rejectionReason: "Documento ilegible, por favor suba una versión más clara",
        reviewedAt: "2026-01-25T09:15:00Z",
        reviewedBy: "Admin",
      },
    ],
    registeredSigners: [
      {
        id: "signer1",
        name: "María García López",
        cuit: "20-12345678-9",
        email: "maria.garcia@empresa.com.ar",
        role: "Presidente",
        isPEP: true,
      },
      {
        id: "signer2",
        name: "Juan Pérez",
        cuit: "20-87654321-0",
        email: "juan.perez@empresa.com.ar",
        role: "Director",
        isPEP: false,
      },
      {
        id: "signer3",
        name: "Carlos Rodríguez",
        cuit: "20-11223344-5",
        email: "carlos.rodriguez@empresa.com.ar",
        role: "Síndico",
        isPEP: false,
      },
    ],
    beneficiaryOwners: [
      {
        id: "bo1",
        name: "María García López",
        cuit: "20-12345678-9",
        nationality: "Argentina",
        ownershipPercentage: 45,
        hasControl: true,
        controlDescription: "Control mayoritario como Presidente del Directorio",
        isPEP: true,
        documentType: "dni",
        documentNumber: "12345678",
        address: "Av. Corrientes 1234, CABA",
        birthDate: "1975-03-15",
      },
      {
        id: "bo2",
        name: "Juan Pérez",
        cuit: "20-87654321-0",
        nationality: "Argentina",
        ownershipPercentage: 30,
        hasControl: false,
        isPEP: false,
        documentType: "dni",
        documentNumber: "87654321",
        address: "Av. Santa Fe 5678, CABA",
        birthDate: "1980-07-22",
      },
      {
        id: "bo3",
        name: "Roberto Fernández",
        cuit: "20-55667788-9",
        nationality: "Argentina",
        ownershipPercentage: 15,
        hasControl: false,
        isPEP: false,
        documentType: "dni",
        documentNumber: "55667788",
        address: "Calle Belgrano 910, Córdoba",
        birthDate: "1968-11-30",
      },
    ],
    beneficiaryOwnersValidated: false,
  },
  {
    id: "2",
    name: "Carlos Rodríguez Martín",
    email: "carlos.rodriguez@srl.com.ar",
    phone: "+54 11 5678-1234",
    cuit: "30-70987654-3",
    companyType: "srl",
    companyName: "Construcciones CRM S.R.L.",
    submittedAt: "2026-01-23T14:45:00Z",
    status: "pending",
    hasPEP: false,
    documents: [
      {
        id: "doc5",
        name: "Contrato Social",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/contrato-social-2.pdf",
        uploadedAt: "2026-01-23T14:45:00Z",
        reviewedAt: "2026-01-24T10:00:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc6",
        name: "Acta",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/acta-2.pdf",
        uploadedAt: "2026-01-23T14:47:00Z",
        reviewedAt: "2026-01-24T10:05:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc7",
        name: "Libro de Socios",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/libro-socios-2.pdf",
        uploadedAt: "2026-01-23T14:50:00Z",
        reviewedAt: "2026-01-24T10:10:00Z",
        reviewedBy: "Admin",
      },
    ],
    registeredSigners: [
      {
        id: "signer4",
        name: "Carlos Rodríguez Martín",
        cuit: "20-33445566-7",
        email: "carlos.rodriguez@srl.com.ar",
        role: "Gerente",
        isPEP: false,
      },
      {
        id: "signer5",
        name: "Laura Fernández",
        cuit: "27-44556677-8",
        email: "laura.fernandez@srl.com.ar",
        role: "Socia",
        isPEP: false,
      },
    ],
    beneficiaryOwners: [
      {
        id: "bo4",
        name: "Carlos Rodríguez Martín",
        cuit: "20-33445566-7",
        nationality: "Argentina",
        ownershipPercentage: 60,
        hasControl: true,
        controlDescription: "Socio Gerente con control de gestión",
        isPEP: false,
        documentType: "dni",
        documentNumber: "33445566",
        address: "Av. Rivadavia 2345, CABA",
        birthDate: "1972-05-10",
      },
      {
        id: "bo5",
        name: "Laura Fernández",
        cuit: "27-44556677-8",
        nationality: "Argentina",
        ownershipPercentage: 40,
        hasControl: false,
        isPEP: false,
        documentType: "dni",
        documentNumber: "44556677",
        address: "Calle San Martín 876, Rosario",
        birthDate: "1985-09-18",
      },
    ],
    beneficiaryOwnersValidated: false,
  },
  {
    id: "3",
    name: "Ana Fernández Soto",
    email: "ana.fernandez@sas.com.ar",
    phone: "+54 11 6789-2345",
    cuit: "30-71567890-2",
    companyType: "sas",
    companyName: "Innovación Digital S.A.S.",
    submittedAt: "2026-01-22T08:15:00Z",
    status: "pending",
    hasPEP: false,
    documents: [
      {
        id: "doc8",
        name: "Contrato Social",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/contrato-social-3.pdf",
        uploadedAt: "2026-01-22T08:15:00Z",
        reviewedAt: "2026-01-23T11:00:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc9",
        name: "Acta",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/acta-3.pdf",
        uploadedAt: "2026-01-22T08:18:00Z",
        reviewedAt: "2026-01-23T11:05:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc10",
        name: "Libro de Socios",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/libro-socios-3.pdf",
        uploadedAt: "2026-01-22T08:20:00Z",
        reviewedAt: "2026-01-23T11:10:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc11",
        name: "Poder",
        type: "pdf",
        status: "approved",
        required: false,
        url: "/documents/poder-3.pdf",
        uploadedAt: "2026-01-22T08:25:00Z",
        reviewedAt: "2026-01-23T11:15:00Z",
        reviewedBy: "Admin",
      },
    ],
    registeredSigners: [
      {
        id: "signer6",
        name: "Ana Fernández Soto",
        cuit: "27-55667788-9",
        email: "ana.fernandez@sas.com.ar",
        role: "Administradora",
        isPEP: false,
      },
    ],
    beneficiaryOwners: [
      {
        id: "bo6",
        name: "Ana Fernández Soto",
        cuit: "27-55667788-9",
        nationality: "Argentina",
        ownershipPercentage: 100,
        hasControl: true,
        controlDescription: "Única accionista y administradora",
        isPEP: false,
        documentType: "dni",
        documentNumber: "55667788",
        address: "Av. Callao 1234, CABA",
        birthDate: "1990-02-28",
      },
    ],
    beneficiaryOwnersValidated: true,
    beneficiaryOwnersValidatedAt: "2026-01-23T12:00:00Z",
    beneficiaryOwnersValidatedBy: "Admin",
  },
  {
    id: "4",
    name: "Pedro Sánchez Ruiz",
    email: "pedro.sanchez@colectiva.com.ar",
    phone: "+54 11 7890-3456",
    cuit: "30-70345678-1",
    companyType: "sociedad_colectiva",
    companyName: "Hermanos Sánchez Sociedad Colectiva",
    submittedAt: "2026-01-21T16:00:00Z",
    status: "pending_pep_approval",
    hasPEP: true,
    pepApprovalStatus: "pending",
    documents: [
      {
        id: "doc12",
        name: "Contrato Social",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/contrato-social-4.pdf",
        uploadedAt: "2026-01-21T16:00:00Z",
        reviewedAt: "2026-01-22T09:00:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc13",
        name: "Acta",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/acta-4.pdf",
        uploadedAt: "2026-01-21T16:05:00Z",
        reviewedAt: "2026-01-22T09:05:00Z",
        reviewedBy: "Admin",
      },
      {
        id: "doc14",
        name: "Libro de Socios",
        type: "pdf",
        status: "approved",
        required: true,
        url: "/documents/libro-socios-4.pdf",
        uploadedAt: "2026-01-21T16:10:00Z",
        reviewedAt: "2026-01-22T09:10:00Z",
        reviewedBy: "Admin",
      },
    ],
    registeredSigners: [
      {
        id: "signer7",
        name: "Pedro Sánchez Ruiz",
        cuit: "20-66778899-0",
        email: "pedro.sanchez@colectiva.com.ar",
        role: "Socio Administrador",
        isPEP: true,
      },
      {
        id: "signer8",
        name: "Miguel Sánchez Ruiz",
        cuit: "20-77889900-1",
        email: "miguel.sanchez@colectiva.com.ar",
        role: "Socio",
        isPEP: false,
      },
    ],
    signersConfig: {
      registeredSigners: ["signer7", "signer8"],
      externalSigners: [],
    },
    beneficiaryOwners: [
      {
        id: "bo7",
        name: "Pedro Sánchez Ruiz",
        cuit: "20-66778899-0",
        nationality: "Argentina",
        ownershipPercentage: 50,
        hasControl: true,
        controlDescription: "Socio administrador con poder de gestión",
        isPEP: true,
        documentType: "dni",
        documentNumber: "66778899",
        address: "Calle Mitre 567, Mendoza",
        birthDate: "1965-12-05",
      },
      {
        id: "bo8",
        name: "Miguel Sánchez Ruiz",
        cuit: "20-77889900-1",
        nationality: "Argentina",
        ownershipPercentage: 50,
        hasControl: false,
        isPEP: false,
        documentType: "dni",
        documentNumber: "77889900",
        address: "Calle Mitre 567, Mendoza",
        birthDate: "1970-04-12",
      },
    ],
    beneficiaryOwnersValidated: false,
  },
];
